name: GBShop
version: '${project.version}'
main: me.giveblock.shopgui.Main
api-version: '1.20'

commands:
  shop:
    description: "Default Shop Command"
    usage: /<command>
    aliases:
      - 'shopgui'
      - 'gbshop'

permissions:
  shopgui