name: GBShop
version: '1.0-SNAPSHOT'
main: me.giveblock.gbshop.Main
api-version: '1.20'

commands:
  shop:
    description: "Default Shop Command"
    usage: /<command>
    aliases:
      - 'shopgui'
      - 'gbshop'

permissions:
  gbshop:
    description: 'Default Shop Command'
    default: true
